# Generated by Django 4.1.2 on 2023-06-26 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parasite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Photograph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.ImageField(upload_to="images/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("reported", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coordinateX", models.CharField(max_length=20)),
                ("coordinateY", models.CharField(max_length=20)),
                ("width", models.CharField(max_length=20)),
                ("height", models.CharField(max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "parasite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uploads.parasite",
                    ),
                ),
                (
                    "photograph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uploads.photograph",
                    ),
                ),
            ],
        ),
    ]
