# Generated by Django 4.1 on 2023-03-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parasiteimage',
            old_name='image',
            new_name='path',
        ),
    ]
