# Generated by Django 4.1 on 2023-03-20 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_rename_image_parasiteimage_path'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParasiteImage',
            new_name='Photograph',
        ),
    ]
