# Generated by Django 4.1 on 2023-03-21 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploads', '0006_alter_user_surname2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinateX', models.CharField(max_length=20)),
                ('coordinateY', models.CharField(max_length=20)),
                ('width', models.CharField(max_length=20)),
                ('height', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('parasite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.parasite')),
                ('photograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.photograph')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='identification',
            constraint=models.UniqueConstraint(fields=('user', 'photograph', 'parasite', 'coordinateX', 'coordinateY', 'width', 'height'), name='unique_indetification'),
        ),
    ]
