# Generated by Django 4.1 on 2023-03-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croppedimage',
            name='file',
            field=models.ImageField(upload_to='images'),
        ),
    ]
