# Generated by Django 4.1 on 2023-03-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_croppedimage_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CroppedImage',
        ),
    ]
