# Generated by Django 4.1 on 2023-03-20 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploads', '0006_alter_user_surname2'),
        ('game', '0003_delete_croppedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordindateX', models.CharField(max_length=20)),
                ('coordindateY', models.CharField(max_length=20)),
                ('width', models.CharField(max_length=20)),
                ('height', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id_parasite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.parasite')),
                ('id_photograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.photograph')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.user')),
            ],
        ),
    ]
