# Generated by Django 4.1 on 2023-03-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identification',
            old_name='coordindateX',
            new_name='coordinateX',
        ),
        migrations.RenameField(
            model_name='identification',
            old_name='coordindateY',
            new_name='coordinateY',
        ),
        migrations.RenameField(
            model_name='identification',
            old_name='id_parasite',
            new_name='parasite',
        ),
        migrations.RenameField(
            model_name='identification',
            old_name='id_photograph',
            new_name='photograph',
        ),
        migrations.RenameField(
            model_name='identification',
            old_name='id_user',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='identification',
            constraint=models.UniqueConstraint(fields=('user', 'photograph', 'parasite', 'coordinateX', 'coordinateY', 'width', 'height'), name='unique_indetification'),
        ),
    ]
